// SPDX-FileCopyrightText: 2026 Marcus Baw and Koloki Ltd
//
// SPDX-License-Identifier: GPL-2.0-or-later

pub mod add;
pub mod analytics;
pub mod api_key;
pub mod app;
pub mod backup;
pub mod backup_s3;
pub mod category;
pub mod category_def;
pub mod common;
pub mod completions;
pub mod config;
pub mod emoji;
pub mod explorer;
pub mod group;
pub mod harden;
pub mod import;
pub mod invite;
pub mod list;
pub mod log;
pub mod manpages;
pub mod notification;
pub mod open;
pub mod palette;
pub mod plugin;
pub mod pm;
pub mod post;
pub mod render;
pub mod sar;
pub mod search;
pub mod setting;
pub(crate) mod ssh;
pub mod tag;
pub mod theme;
pub mod topic;
pub mod update;
pub mod update_log;
pub mod upload;
pub mod user;
pub mod version;
pub mod webhook;
